# Generated by Django 3.0.2 on 2020-01-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_tag', models.CharField(max_length=20)),
                ('gear_type', models.PositiveSmallIntegerField(choices=[(1, 'headphone'), (2, 'hand mic'), (3, 'tripod'), (4, 'camera'), (5, 'tiepin mic')], default=1)),
                ('fosdem_tag', models.CharField(max_length=20)),
                ('notes', models.TextField(max_length=200)),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'expected from rental company'), (2, 'pre FOSDEM inventoried'), (3, 'pre FOSDEM functionality checked'), (4, 'in room'), (5, 'post FOSDEM inventory OK'), (6, 'post FOSDEM NOK (add note!)')], default=1)),
            ],
        ),
    ]
