# Generated by Django 3.0.2 on 2020-01-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogear', '0003_videogear_gear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogear',
            name='fosdem_tag',
            field=models.SlugField(unique=True),
        ),
    ]
