# Generated by Django 3.0.2 on 2020-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogear', '0004_auto_20200115_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogear',
            name='fosdem_tag',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videogear',
            name='notes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videogear',
            name='rental_tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
